### ISSUE TITLE
Unable to change base_dn via ENV variable

### ISSUE THREAD

**Issue by Crazy-Duck** [osixia/container-openldap#142]
When creating a container based on the latest image, the LDAP_BASE_DN environment variable is ignored. The only way to change the base DN is by specifying a domain, but then the root will use "dc=..." for each part of the domain. It is impossible at the moment to configure a X500 style base DN with "l=..", "o=..." etc.

Docker version 17.06.2-ce, build cec0b72
docker-compose version 1.14.0, build c7bdf9e3
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
Minimal docker-compose file reproducing the problem:
```
version: '3.2'
services:
  ldap:
    image: osixia/openldap:latest
    expose:
      - "389"
      - "636"
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_BASE_DN: "dc=mydomain,dc=be"
      LDAP_ORGANISATION: "MyOrg"
```
Screenshot of ldapadmin showing sole available base dn
![local_ldap](https://user-images.githubusercontent.com/11719463/30377593-968d0bb4-9890-11e7-8187-cff38c1bd796.png)

The same issue presents itself when doing a `docker run` specifying the environment variable as a parameter

**Comment by fjakop** [comment]
Same issue here, with docker-compose given as

```
ldap:
    image: osixia/openldap:1.2.4
    command: --loglevel debug
    environment:
      - LDAP_BASE_DN=dc=bar,dc=foo
    ports:
      - 389:389
```

a logon with `cn=admin,dc=bar,dc=foo` does not work, but `cn=admin,dc=example,dc=org` is still working.
