### ISSUE TITLE
Multi master replication

### ISSUE THREAD

**Issue by ssergeby** [osixia/container-openldap#196]
Hi All. anybody has success configuration for multi master ?
SSL(389) and StartTLS(636) - connections works good for both servers.
Replication does not work =((
Containers are running on VM with white IPs and DNS records.
VM hostname and DNS not matched.

My config:

```
version: '3'
services:
    openldap:
      image: osixia/openldap:1.1.11
      volumes:
        # - ./ldap_data:/var/lib/ldap
        # - ./ldap_config:/etc/ldap/slapd.d
        - /etc/ssl/private/:/container/service/slapd/assets/certs
      ports:
        - "636:636"
        - "389:389"
      command: [--copy-service,  --loglevel, info]
      restart: always
      domainname: "ds1.dom.com" # for second server ds2.dom.com
      hostname: "ds1.dom.com" # for second server  ds2.dom.com
      tty: "true"
      stdin_open: "true"
      environment:
        LDAP_LOG_LEVEL: "3"
        LDAP_ORGANISATION: "myorg"
        LDAP_DOMAIN: "myorg.com"
        LDAP_BASE_DN: "dc=myorg,dc=com"
        LDAP_ADMIN_PASSWORD: "admpsss"
        LDAP_CONFIG_PASSWORD: "configpass"
        LDAP_TLS_VERIFY_CLIENT: "try"

        LDAP_TLS: "true"
        LDAP_TLS_ENFORCE: "true"

        LDAP_TLS_CIPHER_SUITE: "SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC"
        LDAP_READONLY_USER: "false"
        LDAP_READONLY_USER_USERNAME: "readonly"
        LDAP_READONLY_USER_PASSWORD: "readonly"
        LDAP_TLS_CRT_FILENAME: "cert.pem"
        LDAP_TLS_KEY_FILENAME: "key.pem"
        LDAP_TLS_CA_CRT_FILENAME: "ca.pem"
        LDAP_RFC2307BIS_SCHEMA: "true"
        LDAP_BACKEND: "hdb"
        LDAP_REPLICATION: "true"
            
        LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn=\"cn=admin,cn=config\" bindmethod=simple credentials=$${LDAP_CONFIG_PASSWORD} searchbase=\"cn=config\" type=refreshAndPersist retrue=\"60 +\" timeout=1 starttls=critical"
        LDAP_REPLICATION_DB_SYNCPROV: "binddn=\"cn=admin,$${LDAP_BASE_DN}\" bindmethod=simple credentials=$${LDAP_ADMIN_PASSWORD} searchbase=\"$${LDAP_BASE_DN}\" type=refreshAndPersist interval=00:00:00:10 retrue=\"60 +\" timeout=1 starttls=critical"
        
        LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ds1.dom.com', 'ldap://ds2.dom.com']"
        KEEP_EXISTING_CONFIG: "false"
        LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
        LDAP_SSL_HELPER_PREFIX: "ldap"

volumes:
    ldap_data:
    ldap_config:
    ldap_cert:
```
