### ISSUE TITLE
Permissions issue using docker compose

### ISSUE THREAD

**Issue by vlizanae** [osixia/container-openldap#285]
When trying to deploy this inside a stack I had problems with the permissions using the following docker-compose.yml: 

```
version: '3'
services:
  ldap-server:
    image: registry:5000/ldap-server
    build:
      context: ./docker-openldap/image
    volumes:
      - ./data:/var/lib/ldap
      - ./config:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636
```

the stack would run but only if it was the first deployment, to run it again I would have to wipe data and config folders even adding `command: --copy-service`. After some trial and error I was able to solve this by setting the environment variables:

```
    environment:
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
      - KEEP_EXISTING_CONFIG=true
```

It may be useful to have this in the readme.
