### ISSUE TITLE
Converting schema to ldif seems to work, but ldif file could not be found

### ISSUE THREAD

**Issue by mwienhold** [osixia/container-openldap#496]
Hello!

I am trying to set up an Openldap server with an extension to the attribute types of a custom object class `customPerson`:

`customPerson.schema`:
```
attributeType ( 2.25.128424792425578037463837247958458780603.2
   NAME 'company'
   EQUALITY caseIgnoreMatch
   SUBSTR caseIgnoreSubstringsMatch
   SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{1024}
   SINGLE-VALUE )

objectClass ( 2.25.128424792425578037463837247958458780603.3
   NAME 'customPerson'
   DESC 'customPerson'
   SUP iNetOrgPerson
   STRUCTURAL
   MAY ( company ) )
```

When I run `docker-compose` my custom schema seems to be converted, but afterwards the generated ldif file can not be found.

`docker-compose.yml`:
```yaml
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: "DC=example,DC=org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
    command: --copy-service --loglevel debug
    volumes:
      - ./.docker/openldap/ldap.conf:/container/service/slapd/assets/ldap.conf
      - ./.docker/openldap/schema/customPerson.schema:/container/service/slapd/assets/config/bootstrap/schema/customPerson.schema
      - ./.docker/openldap/seed:/container/service/slapd/assets/config/bootstrap/ldif/custom
```

Docker's logs:
```
[...]
openldap        | config file testing succeeded
openldap        | sed: can't read customPerson.ldif: No such file or directory
openldap        | sed: can't read customPerson.ldif: No such file or directory
openldap        | sed: can't read customPerson.ldif: No such file or directory
openldap        | sed: can't read customPerson.ldif: No such file or directory
openldap        | sed: can't read customPerson.ldif: No such file or directory
openldap        | sed: can't read customPerson.ldif: No such file or directory
openldap        | sed: can't read customPerson.ldif: No such file or directory
openldap        | sed: can't read customPerson.ldif: No such file or directory
openldap        | sed: can't read customPerson.ldif: No such file or directory
openldap        | sed: can't read customPerson.ldif: No such file or directory
openldap        | mv: cannot stat 'customPerson.ldif': No such file or directory
openldap        | Processing file /container/run/service/slapd/assets/config/bootstrap/schema/mmc/dhcp.ldif
[...]
openldap        | ldap_add: Invalid syntax (21)
openldap        |       additional info: objectClass: value #2 invalid per syntax
openldap        | adding new entry "cn=Test1 Benutzer,dc=example,dc=org"
openldap        |
openldap        | ldap_add: Invalid syntax (21)
openldap        |       additional info: objectClass: value #2 invalid per syntax
openldap        | adding new entry "cn=Test1 Benutzer,dc=example,dc=org"
openldap        | *** /container/run/startup/slapd failed with status 21
openldap        |
openldap        | *** Run commands before finish...
openldap        | *** Killing all processes...
openldap        | 5fcfa45e daemon: shutdown requested and initiated.
openldap        | 5fcfa45e slapd shutdown: waiting for 0 operations/tasks to finish
openldap        | 5fcfa45e slapd stopped.
openldap exited with code 1
```

Am I missing something?

Thank you!
