### ISSUE TITLE
Adding Schema in Kubernetes via ConfigMap fails container start

### ISSUE THREAD

**Issue by jslay-excella** [osixia/container-openldap#625]
Trying to bring up `1.5.0` in kubernetes, bringing schema in via `ConfigMap` with file keys, mounted as a volume to `/container/service/slapd/assets/config/bootstrap/schema`. 

```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-schema
  namespace: ldap
  labels:
    app.kubernetes.io/instance: ldap
    app.kubernetes.io/name: ldap
    app.kubernetes.io/version: 1.5.0
data:
  my.schema: "schema config stuff here"
```

Container Volume Mounts

```YAML
volumeMounts:
  - name: schema
    mountPath: "/container/service/slapd/assets/config/bootstrap/schema"
```

When I do this, the container fails to start and errors out with the following. 

```
***  INFO   | 2022-06-23 09:04:54 | Database and config directory are empty...
***  INFO   | 2022-06-23 09:04:54 | Init new ldap server...
  Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.57+dfsg-1~bpo10+1... done.
  Creating initial configuration... done.
  Creating LDAP directory... done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
rm: cannot remove '/container/service/slapd/assets/config/bootstrap/schema/rfc2307bis.*': No such file or directory
***  ERROR  | 2022-06-23 09:04:55 | /container/run/startup/slapd failed with status 1

***  INFO   | 2022-06-23 09:04:55 | Killing all processes...
```

It appears to be associated with [this line here](https://github.com/osixia/docker-openldap/blob/master/image/service/slapd/startup.sh#L226).

Also, providing such file via ConfigMap would be of no use, as all files mounted via ConfigMap are read-only anyway, and wouldn't be able to delete it. Can we have a check around this instead of just a blind `rm`?
